services:
  expenselog_database:
    image: postgres:16
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  expenselog_app:
    image: expenselog_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - expenselog_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@expenselog_database:5432/app_db

volumes:
  pgdata: 